# -*- coding: utf-8 -*-
"""Data Cleaning_Missing value imputation sklearn II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CsYwOPUGRoh6L0Az6ehwgHqBmvtjBc_F

# Data Cleaning
## Missing value imputation using Scikit-Learn
### Different strategy for Different variables
"""

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

train = pd.read_csv(r"K:\KaustavR25\SKILLZ\Data Science & Analysis, ML\Data-Science_ML----Projects-Resources-main\Study & Resource\Data Cleaning\train.csv")
test = pd.read_csv(r"K:\KaustavR25\SKILLZ\Data Science & Analysis, ML\Data-Science_ML----Projects-Resources-main\Study & Resource\Data Cleaning\test.csv")
print("shape of train df = ", train.shape)
print("shape of test df = ", test.shape)

X_train = train.drop(columns='SalePrice', axis=1)
y_train = train['SalePrice']
X_test = test.copy()
print("shape of X_train df = ", X_train.shape)
print("shape of y_train df = ", y_train.shape)
print("shape of X_test df = ", X_test.shape)

"""## Missing value Imputation"""



